artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/dataingestion
  data_path: data/Bitext_Sample_Customer_Service_Training_Dataset/Training/Bitext_Sample_Customer_Service_Training_Dataset.csv
  train_dir: artifacts/data_ingestion/train
  test_dir: artifacts/data_ingestion/test

data_transformation:
  root_dir: artifacts/data_transformation
  train_path: artifacts/data_ingestion/train/train.csv
  tokenizer_name: bert-base-uncased
  transformed_data_path: artifacts/data_transformation

model_trainer:
  root_dir: artifacts/model_trainer
  model_ckpt: microsoft/deberta-v3-base
  model_save_path: artifacts/model_trainer/trained_model
  num_labels: null  # Will be set dynamically
  epochs: 3
  batch_size: 16
  learning_rate: 2e-5
  loss_function: sparse_categorical_crossentropy
  optimizer: adam
  metrics: 
    - accuracy

