artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/dataingestion
  data_path: data/Bitext_Sample_Customer_Service_Training_Dataset/Training/Bitext_Sample_Customer_Service_Training_Dataset.csv
  train_dir: artifacts/data_ingestion/train
  test_dir: artifacts/data_ingestion/test
